stages:
  ingest:
    cmd: python src/01_data_ingestion.py
    deps:
    - src/01_data_ingestion.py
    outs:
    - data/merge_df.csv
  preprocess:
    cmd: python src/02_preprocessing.py
    deps:
    - data/merge_df.csv
    - src/02_preprocessing.py
    outs:
    - data/clean_merge_df.parquet
  summarize:
    cmd: python src/03_b_t5_summarization.py
    deps:
    - data/clean_merge_df.parquet
    - src/03_b_t5_summarization.py
    outs:
    - outputs/final_top500_product_summary.csv
  apriori:
    cmd: python src/04_apriori_recommender.py
    deps:
    - data/clean_merge_df.parquet
    - src/04_apriori_recommender.py
    outs:
    - models/apriori_recommender.pkl
    - outputs/apriori_rules.csv
  content_cf:
    cmd: python src/05_content_cf_recommender.py
    deps:
    - data/clean_merge_df.parquet
    - src/05_content_cf_recommender.py
